ext {
    mod_id = "bowlingplayergame"
    mod_name = "Bowling Player Game"
    mod_author = "tacowasa059"
}

description = "Game management add-on for Bowling Player."

apply plugin: 'multiloader-common'
apply plugin: 'net.neoforged.moddev.legacyforge'

legacyForge {
    mcpVersion = minecraft_version
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    implementation(project(':common')) {
        capabilities {
            requireCapability "$group:bowlingplayer"
        }
    }
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
